spring:
  application:
    name: diplom

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:file:./data/diplomdb;AUTO_SERVER=TRUE
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  error:
    include-message: always